### ISSUE TITLE
你好，怎么才能去掉左下角的天地图logo

### ISSUE THREAD

**Issue by yanyimiao** [SoulLyoko/vue-tianditu#44]
另外， 我加了Copyright控件也没有效果，不显示任何东西
我的控件内容： { name: "Copyright", id: "234",content:"测试" },

**Comment by SoulLyoko** [comment]
通过css可以隐藏天地图的logo，这样写可以避免影响到自定义添加的版权控件
```css
.tdt-control-copyright.tdt-control > div:not(.tdt-control-copyright) {
  display: none;
}
```
